name: Build and deploy Node.js app to Azure Web App - embedding-test-1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install FastText
        run: |
          cd ./libraries
          git clone https://github.com/facebookresearch/fastText.git
          cd ./fastText
          mkdir build && cd build
          cmake ..
          make && make install
          cd ../../..
          node-gyp configure
          node-gyp build

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'embedding-test-1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6DAF8E2F90F44B518869EA61DBFE2395 }}
          package: .

      - name: Install PM2
        run: npm install pm2 -g

      - name: Start server
        run: pm2 start process.json
